services:
  gateway:
    image: ultri/open-platform-gateway:latest
    container_name: ultri-gateway
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
    env_file: ".env"
    networks:
      - ultri-net
    volumes:
      - "./gateway/config/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"
      - "./gateway/config/account.key:/etc/openresty/account.key"
      - "./gateway/certs/default-service.key:/etc/openresty/default.key"
      - "./gateway/certs/default-service.pem:/etc/openresty/default.pem"
      - "./gateway/html:/usr/local/openresty/nginx/html"
      - "./logs/gateway:/usr/local/openresty/nginx/logs"
    depends_on:
      - api
      - authentic8

  api:
    image: ultri/open-platform-api:latest
    container_name: ultri-api
    ports:
      - "3500:3000"
    env_file: ".env"
    networks:
      - ultri-net
    volumes:
      - "./api/config:/usr/src/api/config"
      - "./api/plugins:/usr/src/api/plugins"
      - "./api/routes:/usr/src/api/routes"
      - "./api/services:/usr/src/api/services"
      - "./api/app.js:/usr/src/api/app.js"

  authentic8:
    image: ultri/authentic8
    restart: unless-stopped
    command: server
    volumes:
      - ./auth/media:/media
      - ./auth/custom-templates:/templates
    env_file:
      - .env
    ports:
      - "${AUTHENTIK_PORT_HTTP:-9000}:9000"
      - "${AUTHENTIK_PORT_HTTPS:-9443}:9443"
    networks:
      - ultri-net

  authentic8worker:
    image: ultri/authentic8
    restart: unless-stopped
    command: worker
    # `user: root` and the docker socket volume are optional.
    # See more for the docker socket integration here:
    # https://goauthentik.io/docs/outposts/integrations/docker
    # Removing `user: root` also prevents the worker from fixing the permissions
    # on the mounted folders, so when removing this make sure the folders have the correct UID/GID
    # (1000:1000 by default)
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./auth/media:/media
      - ./auth/certs:/certs
      - ./auth/custom-templates:/templates
    env_file:
      - .env
    networks:
      - ultri-net

networks:
  ultri-net:
    external: false

