services:

  gateway:
    image: ultri/open-platform-gateway:latest
    container_name: ultri-gateway
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
    env_file: .env
    networks:
     - priv-net
    volumes:
      - './gateway/config/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf'
      - './gateway/config/account.key:/etc/openresty/account.key'
      - './gateway/certs/default-service.key:/etc/openresty/default.key'
      - './gateway/certs/default-service.pem:/etc/openresty/default.pem'  
      - './gateway/html:/usr/local/openresty/nginx/html'
      - './logs/gateway:/usr/local/openresty/nginx/logs'  

  api: 
    image: ultri/open-platform-api:latest
    container_name: ultri-api
    ports:
      - '3333:3000'
    env_file: .env
    networks:
     - priv-net
    volumes:
      - './api/config:/usr/src/api/config'
      - './api/plugins:/usr/src/api/plugins'
      - './api/routes:/usr/src/api/routes'
      - './api/services:/usr/src/api/services'
      - './api/app.js:/usr/src/api/app.js'

networks:
 priv-net:
   external: false