#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  BEGIN;
    ALTER SCHEMA izzup_api OWNER TO  $IZZUP_DB_USER;
    ALTER SCHEMA ultri_auth OWNER TO  $AUTH_DB_USER;
  COMMIT;

EOSQL