#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER"  --dbname "$TENANT_DB_NAME" <<-EOSQL
  BEGIN;
    CREATE USER $IZZUP_DB_USER WITH PASSWORD '$IZZUP_DB_PASS';
    GRANT CONNECT ON DATABASE $TENANT_DB_NAME TO $IZZUP_DB_USER;
    CREATE SCHEMA IF NOT EXISTS izzup_api;
    GRANT USAGE ON SCHEMA izzup_api TO $IZZUP_DB_USER;
    GRANT ALL ON ALL SEQUENCES IN SCHEMA izzup_api TO $IZZUP_DB_USER;
    GRANT ALL ON ALL TABLES IN SCHEMA izzup_api TO $IZZUP_DB_USER;
    GRANT ALL ON ALL FUNCTIONS IN SCHEMA izzup_api TO $IZZUP_DB_USER;
    ALTER ROLE $IZZUP_DB_USER SET search_path = izzup_api,public;
    ALTER SCHEMA izzup_api OWNER TO  $IZZUP_DB_USER;

    CREATE USER $AUTH_DB_USER WITH PASSWORD '$AUTH_DB_PASS';
    GRANT CONNECT ON DATABASE $TENANT_DB_NAME TO $AUTH_DB_USER;
    CREATE SCHEMA IF NOT EXISTS ultri_auth;
    GRANT USAGE ON SCHEMA ultri_auth TO $AUTH_DB_USER;
    GRANT ALL ON ALL SEQUENCES IN SCHEMA ultri_auth TO $AUTH_DB_USER;
    GRANT ALL ON ALL TABLES IN SCHEMA ultri_auth TO $AUTH_DB_USER;
    GRANT ALL ON ALL FUNCTIONS IN SCHEMA ultri_auth TO $AUTH_DB_USER;
    ALTER ROLE $AUTH_DB_USER SET search_path = ultri_auth,public;
    ALTER SCHEMA ultri_auth OWNER TO  $AUTH_DB_USER;
    
  COMMIT;

EOSQL